version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username=2681997 --password=Dell@123ak          
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t awscode:aws2 .
      - docker tag awscode:aws2 2681997/awscode:aws2
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 2681997/awscode:aws2
